# Generated by Django 4.1.5 on 2023-01-29 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_submission_for_question_and_more"),
        ("users", "0003_team_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="current_question",
        ),
        migrations.AddField(
            model_name="team",
            name="current_offline_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.offlinequestion",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="current_online_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.onlinequestion",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="total_points",
            field=models.IntegerField(default=0),
        ),
    ]
