# Generated by Django 4.1.5 on 2023-03-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_team_current_question_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="levelup_time",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
