# Generated by Django 4.2.1 on 2023-05-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_ipaddress_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="school_user_id",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
