# Generated by Django 4.1.5 on 2023-01-29 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_submission_by_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="for_question",
        ),
        migrations.AddField(
            model_name="submission",
            name="for_offline_question",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.offlinequestion",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="for_online_question",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.onlinequestion",
            ),
        ),
    ]
